### ISSUE TITLE
Charlotte, NC coordinates return "Asia/Kashgar" instead of "America/New_York"

### ISSUE THREAD

**Issue by umpc** [bradfitz/latlong#4]
Hello. When using 35.2269, 80.8433, which is in the eastern U.S., I'm getting "Asia/Kashgar."

**Comment by bradfitz** [comment]
What was the resolution?

**Comment by umpc** [comment]
It turned out to be my own silly mistake. At the time, I wasn't validating lat/long input yet, and mistakenly dropped the negative sign that's supposed to be in front of the longitude.

P.S. Thanks for this incredibly useful library!
